# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "set in variables.tfvars"
}

# name of zip file to deploy, generated by 'dotnet build' command
variable "zip_file_name" {
  type    = string
  default = "set in variables.tfvars"
}


# Resource tag:
variable "tag_app_group" {
  type = string
  default = "set in variables.tfvars"
}

variable "ECS_INSTANCE_ID" {
  type = string
  default = "set in variables.tfvars"
}