# see: https://hub.docker.com/_/composer
FROM composer:2@sha256:4d71c3c2109c61d5415544264b59ad4087e4c5b7244481723664138fd36d5040 AS composer

# see: https://hub.docker.com/_/php/tags?name=alpine
FROM php:8.2.33-fpm-alpine3.23@sha256:5ca8e8ba2470d328ca8c43c3bff8c05ed9f48b8fa201b62d8792a0954c727adc

ARG DOCKER_BUILD_TIMESTAMP=unknown
ENV DOCKER_BUILD_TIMESTAMP=${DOCKER_BUILD_TIMESTAMP}

ENV HOME=/home/paas_user \
    GROUP_ID=1003 \
    GROUP_NAME=paas_user \
    USER_ID=1003 \
    USER_NAME=paas_user \
    TZ=Etc/UTC

COPY --from=composer /usr/bin/composer /usr/local/bin/composer

RUN apk add --no-cache tzdata nginx && \
    addgroup -g ${GROUP_ID} ${GROUP_NAME} && \
    adduser -u ${USER_ID} -G ${GROUP_NAME} -D ${USER_NAME}

WORKDIR ${HOME}

COPY --from=myapp composer.json ${HOME}
COPY --from=myapp src ${HOME}/src

RUN composer install --no-dev --no-interaction --optimize-autoloader

COPY nginx.conf ${HOME}/nginx.conf
COPY entrypoint-nginx.sh ${HOME}/entrypoint-nginx.sh

RUN sed -i 's|listen = /run/php/php-fpm.sock|listen = 127.0.0.1:9000|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^user = .*|;user = paas_user|; s|^group = .*|;group = paas_user|' /usr/local/etc/php-fpm.d/www.conf && \
    mkdir -p /var/lib/nginx/logs /var/lib/nginx/tmp /var/log/nginx /run/nginx && \
    chown -R ${USER_ID}:${GROUP_ID} /var/lib/nginx /var/log/nginx /run/nginx ${HOME} && \
    chmod -R 550 ${HOME}

EXPOSE 8000

USER ${USER_NAME}

ENTRYPOINT ["sh", "/home/paas_user/entrypoint-nginx.sh"]
